:title: java.time
include::_theme/theme.adoc[]
:src: time

_Wer die Zeitzone nicht kennt hat schnell Weihnachten verpennt_

== Es war einmal...

vor einigen Java Releases...
[.fragment]
in einer längst vergangenen Zeit...
[.fragment]
oder etwa doch nicht?

=== java.util.Date

Zeitpunkt in Millisekunden seit 1.1.1970

[source,java,indent=0]
----
include::{src}/JavaUtil.java[tag=date]
----

[.fragment]
🤮

=== java.util.Calendar

Ortsgebundene Zeit, über java.util.Date gestülpt

[source,java,indent=0]
----
include::{src}/JavaUtil.java[tag=calendar]
----

[.fragment]
🤮🤮


=== java.text.SimpleDateFormat

Formatieren und parsen von java.util Zeiten

[source,java,indent=0]
----
include::{src}/JavaUtil.java[tag=format]
----

[.fragment]
🤮🤮🤮

=== Arbeiten mit Calendar

Ohne (viele) Worte...

[source,java,indent=0]
----
include::{src}/JavaUtil.java[tag=calculate]
----

[.fragment]
🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮

== Zeitzonen

Gibt's zum Download im Internet:
https://www.iana.org/time-zones

=== IANA TZ Database

[source,text,indent=0]
----
include::{src}/zones.txt[lines=1..17]
----

=== Zeitzonen in Deutschland

[source,text,indent=0]
----
include::{src}/zones.txt[lines=19..28]
----

=== Java Zeitzonen

In der JRE enthalten:
[source,shell,indent=0]
----
$JAVA_HOME/lib/tzdb.dat
$JAVA_HOME/lib/tzmappings
----

=== Java Laufzeit Umgebung

System Umgebung (System.getProperties())
[source,text,indent=0]
----
include::{src}/UserProperties.java[tag=sysprops]
----

Benutzer Eigenschaften (System.getenv())
[source,text,indent=0]
----
include::{src}/UserProperties.java[tag=sysenv]
----

== Java 8: JSR 310

aber Rettung naht...

=== java.time.Instant

[source,java,indent=0]
----
include::{src}/JavaTime.java[tag=instant]
----

=== java.time.LocalDate

[source,java,indent=0]
----
include::{src}/JavaTime.java[tag=localDate]
----

=== java.time.LocalDateTime

[source,java,indent=0]
----
include::{src}/JavaTime.java[tag=localDateTime]
----

=== java.time.LocalTime

[source,java,indent=0]
----
include::{src}/JavaTime.java[tag=localTime]
----

=== java.time.OffsetDateTime

[source,java,indent=0]
----
include::{src}/JavaTime.java[tag=offsetDateTime]
----

=== java.time.OffsetTime

[source,java,indent=0]
----
include::{src}/JavaTime.java[tag=offsetTime]
----

=== java.time.ZonedDateTime

[source,java,indent=0]
----
include::{src}/JavaTime.java[tag=zonedDateTime]
----

== Rausgeben und Einlesen

Standards

[source,java,indent=0]
----
include::{src}/JavaTime.java[tag=defaultFormat]
----

=== Benutzerdefiniert

[source,java,indent=0]
----
include::{src}/JavaTime.java[tag=customFormat]
----

=== JSON Mapping

Jackson
[source,java]
----
new ObjectMapper()
    .registerModule(new JavaTimeModule());
----

Gson
[source,java]
----
new GsonBuilder()
    .registerTypeAdapterFactory(
		new GsonJava8TypeAdapterFactory()
	).create()
----

== Zeitreisen / -rechnen
 
Grundrechenarten
[source,java,indent=0]
----
include::{src}/Calc.java[tag=plusMinus]
----

=== Dauer und Perioden

[source,java,indent=0]
----
include::{src}/Calc.java[tag=advanced]
----

=== Zeitzonentreue

